_target_: models.nocs.get_nocs_resnet50_fpn
maskrcnn_weights: 
  _target_: hydra.utils.get_object
  path: torchvision.models.detection.mask_rcnn.MaskRCNN_ResNet50_FPN_Weights.DEFAULT
nocs_loss: 
  _target_: hydra.utils.get_method
  path: torch.nn.functional.cross_entropy
nocs_num_bins: 32
nocs_loss_mode: classification
multiheaded_nocs: True

load: