_target_: models.nocs.get_nocs_resnet50_fpn

num_classes: 7

# pretrained mrcnn weights
maskrcnn_weights: 
  _target_: hydra.utils.get_object
  path: torchvision.models.detection.mask_rcnn.MaskRCNN_ResNet50_FPN_Weights.DEFAULT

# nocs head config
nocs_head:
  num_bins: 1
  mode: regression
  head_per_channel: True
  # layers:

# nocs loss config
nocs_loss:
  _target_: torch.nn.ModuleDict
  modules:
    'mse':
      # _target_: torch.nn.MSELoss
      _target_: models.losses.symmetry_aware_loss.SymmetryAwareLoss

# pretrained nocs weights
load:  # Set to load checkpoint

# rpn_nms_thresh: 0.3   # default -> 0.7
# rpn_score_thresh: 0.5 # default -> 0.0
box_score_thresh: 0.7
# box_nms_thresh:   0.3
