_target_: models.nocs.get_nocs_resnet50_fpn

num_classes: 7

# pretrained mrcnn weights
maskrcnn_weights: 
  _target_: hydra.utils.get_object
  path: torchvision.models.detection.mask_rcnn.MaskRCNN_ResNet50_FPN_Weights.DEFAULT

# pretrained nocs weights
load:

# nocs loss config
nocs_loss: 
  _target_: models.discriminator.MultiClassDiscriminatorWithOptimizer
  logger: 
    _target_: hydra.utils.get_method
    path: wandb.log
  num_classes: 7 # Number of discriminators to create
  optim_args:
    lr: 0.0004
    betas: [0.5, 0.999]
    # weight_decay: 1e-6

  feat_ch: 128


#### NOCS head config ##########################
nocs_head_params:
  num_bins: 1
  mode: regression
  head_per_channel: True
  # layers: 

#### Post processing params ####################

# rpn_nms_thresh: 0.3   # default -> 0.7
# rpn_score_thresh: 0.5 # default -> 0.0
box_score_thresh: 0.7
# box_nms_thresh:   0.3