_target_: torchvision.models.detection.maskrcnn_resnet50_fpn

weights: 
  _target_: hydra.utils.get_object
  path: torchvision.models.detection.mask_rcnn.MaskRCNN_ResNet50_FPN_Weights.DEFAULT

load: # not used