_target_: models.mrcnn.maskrcnn_resnet50_fpn_adjusted_class_count
num_classes: 7

weights: 
  _target_: hydra.utils.get_object
  path: torchvision.models.detection.mask_rcnn.MaskRCNN_ResNet50_FPN_Weights.DEFAULT

# rpn_nms_thresh: 0.3   # default -> 0.7
# rpn_score_thresh: 0.5 # default -> 0.0
box_score_thresh: 0.7
# box_nms_thresh:   0.3


load: # not used