defaults:
  - model: base
  - data: original_nocs
  - optimization: frozen_backbone
  - _self_

project_name: NOCS
run_name:     base

device: cuda:0
checkpoint_dir: ./checkpoints/base/${now:%Y-%m-%d_%H-%M-%S}
retain_n_checkpoints: 5   # Checkpoints to retain
log: true                 # Whether to push logs to wandb

num_epochs: 50            # Epochs to train for
batches_before_save: 100  # Batches before saving a checkpoint
batches_before_eval: 50   # Batches before evaluating
num_eval_batches: 5       # Batches to evaluate on

model:
  num_classes: 7
  override_num_classes: True
  
hydra:
    run:
        dir: outputs/${project_name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}