defaults:
  - model: base
  - data: original_nocs
  - optimization: frozen_backbone
  - _self_

log: true                 # Whether to push logs to wandb
logger:
  project: gan-nocs
  entity:  rpm-collab
  name:    train_new_main

device: cuda:0
checkpoint_dir: ./checkpoints/${logger.project}/${logger.name}/${now:%Y-%m-%d_%H-%M-%S}
retain_n_checkpoints: 5   # Checkpoints to retain

num_epochs: 200            # Epochs to train for
batches_before_save: 100  # Batches before saving a checkpoint
batches_before_eval: 50   # Batches before evaluating
num_eval_batches: 5       # Batches to evaluate on

model:
  num_classes: 7
  box_score_thresh: 0.7
  
hydra:
    run:
        dir: ${checkpoint_dir}