defaults:
  - model: base
  - data: original_nocs
  - _self_

log: true                 # Whether to push logs to wandb
logger:
  project: gan-nocs
  entity:  rpm-collab
  name:    train_original_symmetry

device: cuda:0
checkpoint_dir: ./checkpoints/${logger.project}/${logger.name}/${now:%Y-%m-%d_%H-%M-%S}
retain_n_checkpoints: 2   # Checkpoints to retain

num_epochs: 1000          # Epochs to train for
batches_before_save: 100  # Batches before saving a checkpoint
batches_before_eval: 50   # Batches before evaluating
num_eval_batches: 5       # Batches to evaluate on

hydra:
    run:
        dir: ${checkpoint_dir}

mAP_configs:

optimization:
  _target_: utils.optimizers.InitHydraOptimizers
  optim_cfgs: 
    - 
      type: 
        _target_: hydra.utils.get_method
        path: torch.optim.Adam
      args:
        lr: 0.0001
        weight_decay: 0.0001
        betas: [0.9, 0.99]
  param_cfgs: 
    - [roi_heads, rpn, fpn]