defaults:
  - model: base
  - data: base
  - optimization: base

project_name: torch-nocs-classification
run_name:     basic
num_epochs: 5
batches_before_eval: 5
checkpoint_dir: ./checkpoints/nocs_classification/${now:%Y-%m-%d_%H-%M-%S}
device: cuda:0
