# # Base Model
# defaults:
#   - base
#   - _self_
# model:
#   load: 
#     ignore_keys: []
#     # path: checkpoints/gan-nocs/base-no-real/2023-09-22_17-49-23/0199_000165.pth
#     path: checkpoints/gan-nocs/base-no-real/2023-10-17_17-44-45/0359_000000.pth
# logger:
#   name: original-no-real-labeles
#   project: gan-nocs-eval
# num_eval_batches: 



# GAN  Model - no real
defaults:
- gan
- _self_
- override model: gan-multiloss
model:
  load: 
    ignore_keys: [nocs_loss]
    # path: checkpoints/gan-nocs/gan-no-real-labels/2023-09-21_17-22-36/0095_000100.pth
    path: checkpoints/gan-nocs/multiloss-with-rates/2023-10-20_18-32-33/0135_000000.pth
logger:
  name: eval-multiloss-with-rates
  project: gan-nocs-eval
num_eval_batches: 



# # GAN Model
# defaults:
# - gan
# - override model:  gan
# - _self_
# model:
#   load: 
#     ignore_keys: [nocs_loss]
#     path: checkpoints/gan-nocs/gan-unbalanced/2023-09-21_11-02-48/0147_000000.pth
# logger:
#   name: gan-
#   project: gan-nocs-eval
# num_eval_batches: 50


device: cuda:0
log: True

mAP_configs:
  degree_thresholds_start: 0
  degree_thresholds_end: 61
  degree_thresholds_step: 1
  shift_thresholds_start: 0
  shift_thresholds_end: 1
  shift_thresholds_steps: 31
  shift_thresholds_multiplier: 15
  iou_3d_thresholds_start: 0
  iou_3d_thresholds_end: 1
  iou_3d_thresholds_steps: 101
  iou_pose_thres: 0.1
  use_matches_for_pose: true
  synset_names: ${data.synset_names}
  print_result: true