defaults:
  - base
  - _self_
device: cpu

log: True
model:
  load: /home/kdesingh/chada022/torch_nocs/checkpoints/gan-nocs/train_new_main/2023-09-22_00-08-13/0148_000100.pth
    
  #rpn_nms_thresh: 0.7   # default -> 0.7
  # rpn_score_thresh: 0.5 # default -> 0.0

  box_score_thresh: 0.7
  # box_nms_thresh:   0.3

log_mAP_vals: 
  do_log: True
  degree_thresholds_start: 0
  degree_thresholds_end: 61
  degree_thresholds_step: 1
  shift_thresholds_start: 0
  shift_thresholds_end: 1
  shift_thresholds_steps: 31
  shift_thresholds_multiplier: 15
  iou_3d_thresholds_start: 0
  iou_3d_thresholds_end: 1
  iou_3d_thresholds_steps: 101
  iou_pose_thres: 0.1
  use_matches_for_pose: true


logger:
  name: test_umeyama

num_eval_batches: 10