defaults:
  - base
  - override model:        gan
  - _self_

log:    True
logger:
  name: gan

device:              cuda:1
checkpoint_dir: ./checkpoints/${logger.project}/${logger.name}/${now:%Y-%m-%d_%H-%M-%S}

model:
  nocs_loss:
    num_classes: 7  # number of discriminators to use

optimization:
  optimizer: 
    lr: 0.0001
    weight_decay: 1e-6

