defaults:
  - base
  - override model:        gan
  - _self_

log:    True
logger:
  name: gan

device:              cuda:1

model:
  nocs_loss:
    num_classes: 7  # number of discriminators to use

optimization:
  optimizer: 
    lr: 0.0001
    weight_decay: 1e-6

