defaults:
  - base
  - override model:  gan-multiloss
  - _self_

log:    True
logger:
  name: gan-multiloss

device: cuda:0

optimization:
  _target_: utils.optimizers.InitHydraOptimizers  
  optim_cfgs: 
    -
      type: 
        _target_: hydra.utils.get_method
        path: torch.optim.Adam
      args:
        lr: 0.0001
        betas: [0.9, 0.99]
        weight_decay: 1e-6
    -
      type: 
        _target_: hydra.utils.get_method
        path: torch.optim.Adam
      args:
        lr: 0.0001
        betas: [0.5, 0.99]
        weight_decay: 1e-6
  param_cfgs:
    - ['fpn', 'rpn', 
       'box_roi_pool', 'box_head', 'box_predictor', 
       'mask_roi_pool', 'mask_head', 'mask_predictor']
    - ['nocs_head']