defaults:
  - base
  - override model:  gan
  - _self_

log:    True
logger:
  name: gan

device:              cuda:0

model:
  use_unlabeled_nocs: True  # When set to true, images with no nocs will train the generator

  # load: 
  #   path: checkpoints/gan-nocs/gan-no-real-labels/2023-09-21_17-22-36/0095_000100.pth
  #   ignore_keys: 
    
  # load: 
  #   path: checkpoints/gan-nocs/base-continuous/2023-09-21_11-00-56/0104_000000.pth
  #   ignore_keys: ['discriminator']


  # feat_ch: 16

optimization:
  optimizer: 
    _target_: torch.optim.Adam
    lr: 0.0002
    betas: [0.5, 0.99]
    # weight_decay: 1e-6