defaults:
  - base
  - override model:  gan-multiloss
  - _self_

log:    True
logger:
  name: gan-multiloss

device: cuda:0

optimization:
  optimizer: 
    _target_: torch.optim.Adam
    lr: 0.0002
    betas: [0.5, 0.99]
    weight_decay: 1e-6
  parameters: [roi_heads, rpn, fpn]
  
  # multiple: True
  # optimizers: 
  #     -
  #       _target_: torch.optim.Adam
  #       lr: 0.0002
  #       betas: [0.5, 0.99]
  #       weight_decay: 1e-6
  #     - 
  #       _target_: torch.optim.Adam
  #       lr: 0.0002
  #       betas: [0.5, 0.99]
  #       weight_decay: 1e-6

  # parameters:
  #   - ['backbone', 'fpn', 'rpn', 'roi_heads']
  #   - ['nocs_head']
  #   - ['discriminator']