defaults:
  - base
  - override optimization: frozen_backbone
  - override model:        gan
  - override data:         original_nocs
  - _self_

run_name:            gan_original_data
device:              cuda:1
log:                 True
num_epochs:          200
checkpoint_dir:     ./checkpoints/gan/${now:%Y-%m-%d_%H-%M-%S}

model:
  num_classes: 7
  override_num_classes: True
  nocs_loss:
    num_classes: 7  

optimization:
  optimizer: 
    lr: 0.0001
    weight_decay: 1e-6

