defaults:
  - base
  - override model:        gan
  - _self_

log:    True
logger:
  name: gan

device:              cuda:1

model:
  use_unlabeled_nocs: True  # When set to true, images with no nocs will train the generator
  nocs_loss:
    num_classes: 7  # number of discriminators to use
  
  load: 
    path: checkpoints/gan-nocs-debugging/base-continuous/2023-09-21_09-26-34/0002_000000.pth
    ignore_keys: ['discriminator']

optimization:
  optimizer: 
    _target_: torch.optim.Adam
    lr: 0.0001
    betas: [0.5, 0.99]
    # weight_decay: 1e-6