defaults:
  - base
  - override optimization: frozen_backbone
  - override data:         multiview
  - override model:        multiview
  - _self_

run_name:     multiview_batch5x5_alignment
device:       cuda:1
