defaults:
  - frozen_backbone

run_name: 25_class_frozen_backbone
device: cuda:0

# Update the number of classes
model:
  num_classes: 25
  override_num_classes: True





  
# # Old data
# data:
#   training:
#     dir: ./data/old-habitat-gen/200of100scenes_26selectChairs/train
#     loader:
#       batch_size: 5