defaults:
  - base
  
run_name: old_data
device: cuda:0

data:
  training:
    dataset:
      data_dir: ./data/old-habitat-gen/200of100scenes_26selectChairs/train
  testing:
    dataset:
      data_dir: data/old-habitat-gen/200of100scenes_26selectChairs/test