defaults:
  - base
  - override model:        base
  - override optimization: frozen_backbone
  - override data:         original_nocs
  - _self_

run_name:            original_nocs_data
device:              cuda:0
log:                 True
num_epochs:          5
checkpoint_dir:     ./checkpoints/nocs_classification/${now:%Y-%m-%d_%H-%M-%S}

model:
  num_classes: 10
  override_num_classes: True

