defaults:
  - base
  
# model:
#   load: /home/baldeeb/Code/pytorch-NOCS/checkpoints/nocs_classification/2023-05-18_15-42-57/new_eval_metrics_0.pth

run_name: with_aug
device: cuda:1

data:
  training:
    loader:
      collate_fn:
        _target_: habitat_datagen_util.utils.collate_tools.TransformImagesAndCollate
  testing:
    loader:
      collate_fn:
        _target_: habitat_datagen_util.utils.collate_tools.TransformImagesAndCollate